"""rename api_usage_metrics to ai_consumption_metrics and drop endpoint column

Revision ID: 308b45344852
Revises: b01ecd748fd0
Create Date: 2026-02-06 16:10:57.064890

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "308b45344852"
down_revision: str | Sequence[str] | None = "b01ecd748fd0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_consumption_metrics",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("response_time_ms", sa.Integer(), nullable=False),
        sa.Column("openai_cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("tokens_used", sa.Integer(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(op.f("ix_api_usage_metrics_created_at"), table_name="api_usage_metrics")
    op.drop_table("api_usage_metrics")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_usage_metrics",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), autoincrement=False, nullable=False),
        sa.Column("endpoint", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("session_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("cache_hit", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("response_time_ms", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("openai_cost_usd", sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("tokens_used", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("prompt_tokens", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("completion_tokens", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("api_usage_metrics_pkey")),
    )
    op.create_index(op.f("ix_api_usage_metrics_created_at"), "api_usage_metrics", ["created_at"], unique=False)
    op.drop_table("ai_consumption_metrics")
    # ### end Alembic commands ###
