"""add token columns to api_usage_metrics

Revision ID: b01ecd748fd0
Revises: cd9e66b6a9ce
Create Date: 2026-02-06 12:50:07.004624

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b01ecd748fd0"
down_revision: str | Sequence[str] | None = "cd9e66b6a9ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("api_usage_metrics", sa.Column("tokens_used", sa.Integer(), nullable=True))
    op.add_column("api_usage_metrics", sa.Column("prompt_tokens", sa.Integer(), nullable=True))
    op.add_column("api_usage_metrics", sa.Column("completion_tokens", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_usage_metrics", "completion_tokens")
    op.drop_column("api_usage_metrics", "prompt_tokens")
    op.drop_column("api_usage_metrics", "tokens_used")
    # ### end Alembic commands ###
